### ISSUE TITLE
VAC and Resolver.

### ISSUE THREAD

**Issue by Lexiyx** [HadenGrenade/StarLight-V3-MAIN#1]
Im just writing to inform you that the cheat is most likely detect.
And the resolver feature is [ not working well/is broken. ]

I just wrote it to give you the information and other than that I think it works well. Except for minor bugs.

**Comment by HadenGrenade** [comment]
hey, yeah i removed the resolver as i wanted to keep it private lol. if you want it feel free to pm me ahhah. if you want it to be UD, just download CSGHOST from unknowncheats

**Comment by Lexiyx** [comment]
CSGhosts VAC Bypass was recently fixed. So Im not sure if there is a newer version I know it is.

When you say "i removed resolver" Im sorry, I realize that Resolver is hollow, :D.
